name: flutterui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 0.4.4
  firebase_analytics:
  cloud_firestore:
  firebase_auth: 0.15.3
  firebase_storage:
  google_sign_in: ^4.1.1
  provider: ^4.0.1
  image_picker_modern: ^0.4.12+3
  image_cropper: ^1.2.1
  cached_network_image: ^2.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0
  firebase_messaging: ^6.0.12
  multi_image_picker: ^4.6.2
  flutter_facebook_login: ^3.0.0
  url_launcher: ^4.2.0+3
  firebase_dynamic_links: ^0.5.0+11
  share: ^0.6.3+6
  photo_view: ^0.9.2
  file_picker: ^1.9.0+1
  csv: ^4.0.3
  camera: ^0.5.8+2
  video_player: ^0.10.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_animations: ^1.3.12
  sliding_up_panel: ^1.0.0
  fading_edge_scrollview: ^1.1.0
  page_transition: ^1.1.5
  flutter_icons: ^1.0.0+1
  flutter_fadein: ^1.1.1
  bottom_navy_bar: ^5.3.2
  configurable_expansion_tile:
  marquee: ^1.3.1
  carousel_slider: ^1.4.1




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - assets/images/a_dot_burr.jpeg
  #  - assets/images/a_dot_ham.jpeg
  
  # or to include all assets from a directory do this:
  # assets:
  #   - assets/images/
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  assets:
    - assets/images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Bold.otf
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: Gibson
      fonts:
            - asset: assets/fonts/Gibson-Regular.ttf
              weight: 500
            - asset: assets/fonts/Gibson-SemiBold.otf
              weight: 700
            - asset: assets/fonts/Gibson-Bold.ttf
    - family: Sf
      fonts:
        - asset: assets/fonts/sf_display/SF-Pro-Display-Light.otf
          weight: 200
        - asset: assets/fonts/sf_display/SF-Pro-Display-Regular.otf
          weight: 300
        - asset: assets/fonts/sf_display/SF-Pro-Display-Medium.otf
          weight: 400
        - asset: assets/fonts/sf_display/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf_display/SF-Pro-Display-Bold.otf
          weight: 800
        - asset: assets/fonts/sf_display/SF-Pro-Display-Heavy.otf
    - family: Sf-r
      fonts:
        - asset: assets/fonts/sf_rounded/SF-Pro-Rounded-Light.otf
          weight: 200
        - asset: assets/fonts/sf_rounded/SF-Pro-Rounded-Regular.otf
          weight: 300
        - asset: assets/fonts/sf_rounded/SF-Pro-Rounded-Medium.otf
          weight: 400
        - asset: assets/fonts/sf_rounded/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf_rounded/SF-Pro-Rounded-Bold.otf
          weight: 800
        - asset: assets/fonts/sf_rounded/SF-Pro-Rounded-Heavy.otf
          weight: 900
    - family: Sf-t
      fonts:
        - asset: assets/fonts/sf_text/SF-Pro-Text-Light.otf
          weight: 200
        - asset: assets/fonts/sf_text/SF-Pro-Text-Regular.otf
          weight: 300
        - asset: assets/fonts/sf_text/SF-Pro-Text-Medium.otf
          weight: 400
        - asset: assets/fonts/sf_text/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf_text/SF-Pro-Text-Bold.otf
          weight: 800
        - asset: assets/fonts/sf_text/SF-Pro-Text-Heavy.otf
          weight: 900